config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {registrations: 'registrations',sessions: 'sessions',omniauth_callbacks: "omniauth_callbacks"}
  resources :sliders

  resources :news
  #get 'friends/new'
  resources :mailbox   
  resources :friends  
  resources :contacts 

  resources :categories do
    resources :bibles do
      resources :chapters
    end
  end

  # resources :bibles do
  #   resources :chapters
  # end

  get 'radio/index'

  resources :audios 

  resources :albums do
    resources :audios  
  end 
  get 'welcome/album_url'
  get 'welcome/video_details'
  get 'welcome/audio_details'
  get 'welcome/album_details'
  resources :daily_breads
  resources :videos
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/contact'
    get 'welcome/about'
  # devise_for :admins  
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  name       :string
#  video      :string
#  created_at :datetime
#  updated_at :datetime
#

class Video < ActiveRecord::Base
	mount_uploader :video, VideoUploader

	def set_success(format, opts)
    	self.success = true
    end
     validates :name, :presence => true
 	 validates :video, :presence => true

 	 def self.search(search)
   	  where("name like ?", "%#{search}%") 
 	 end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
   before_filter :loged_in?, :only => [:new,:create, :edit, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    # @videos = Video.all
    #  @videos_bottom_pagiantion  = Video.paginate(:page => params[:page], :per_page => 3)
    if params[:search] 
      @videos = params[:search].blank? ? Video.paginate(:page => params[:page], :per_page => 10) : Video.search(params[:search]).order("created_at DESC") 
    else
      @videos = Video.paginate(:page => params[:page], :per_page => 10)
      @videos_bottom_pagiantion  = Video.paginate(:page => params[:page], :per_page => 10)
    end 

  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videosall = Video.all
    @video_first=Video.first
    @album_first=Album.first
    
    @video = Video.find(params[:id])
    @videos=Video.where.not(id: @video.id)
     @videos_bottom_pagiantion  = Video.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end
  
  def contact
    video      = params[:video]
    respond_to do |format|
    format.json { render :json => { :video => video} }
    end
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :video)
    end
    def loged_in?
      redirect_to root_path
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_videos.html.erb
<% if (@videos.empty?) %>
    <center><p>No videos found.</p></center>
  <%else%>
  <% @videos.each do |video| %> 
    <li class="inspiration animated" data-gen="fadeInLeft"  data-content="#Audio_1">
        <div class="thumb">
            <div class="view">
            <a href="javascript: void(0)" class="button video_id" data-id="<%= video.id %>">Play</a>
            </div>
            <img src="<%= video.video_url(:thumb) %>" alt="Pic" class="img-responsive"/>
        </div>
        <div class="short_de">
            <h4><a class="colio-link" href="#"><%= video.name%></a></h4>
            <p>Details</p>
        </div>
    </li>  
  <%end%>  
<%end%> 

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<!-- CONTENT BLOCK { -->
<div class="content_box yellow_box">
    
    <div class="main_head page_head text-center">
        <h1 class="head_1 animated" data-gen="fadeInUp">Videos</h1>
    </div>
    <div class="clearfix"></div> 

    <section class="block_1">
      <div class="padding_20 margin_b15 form_style1">
      <div class="col-xs-12">
           
        <%= form_tag(videos_path, :method => "get", class: "form-horizontal", id: "video_search") do %>
          <div class="form-group padding_r20">
              <div class="col-xs-6 col-md-12"> 
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Videos", id: "srch-term" %>
              </div> 
          </div>  
        <% end %> 
        </div>
        </div>
     </section> 
    <div class="clearfix"></div> 
    <div class="video_player_h_s">
       <a class="player-close pull-right" href="javascript: void(0)">
         <%= image_tag "audio-close.png"%>
      </a>
        <div class="main"> 
          <%= render 'shared/video' %>
        </div>
    </div>
    <div class="audio_albums clearfix">
      <ul class="album_list list-unstyled" id="videos_list"> 
           <div id="video_render"><%= render 'videos' %></div>
      </ul>
    </div> 
    <div class="clearfix"></div> 
    
     
    <div class="pag_unstyled">  
      <ul class="pagination">
        <%= will_paginate @videos_bottom_pagiantion,renderer: BootstrapPagination::Rails,remote: true,:page_links => false %>
      </ul>
    </div>
    <script type="text/javascript">
 
$(document).ready(function() {
  $('div.video_player_h_s').hide();
  $("#video_search input").keyup(function() {
      $.get($("#video_search").attr("action"), $("#video_search").serialize(), null, "script");
      return false;
    });
  $("body").on("click",".video_id",function() {

    $('#videos_list li').removeClass('colio-active-item');
      $(this).closest( "li" ).addClass('colio-active-item');
  var videoid = $(this).attr("data-id");  
  $("#jquery_jplayer_3").jPlayer("destroy");
      $.ajax({ 
        type: 'GET',
        url: '/welcome/video_details',
        data: { 
                 video_id: videoid 
                  },
        success: function(data,status,xhr){ 
          $('div.video_player_h_s').show();
           $(window).scrollTop($(window).scrollTop()+100);
          $('#jquery_jplayer_3').jPlayer({
            ready:function (event) {
                $(this).jPlayer("setMedia", {
                    m4v:data.video.url
                }).jPlayer("play");   //attemp to play media
            }, 
            supplied:"m4v",
            cssSelectorAncestor: "#jp_container_3"
        }); 
           
        },
        error: function(xhr,status,error){
          console.log(xhr);
           
        }
      }); 
       
  });

  $('.player-close').on("click",function(){
  $("#jquery_jplayer_3").jPlayer("destroy");
   $('div.video_player_h_s').hide();
  });

  //Initialize Original height of content_box
  var $content_box = $('.content_box');
  var content_box_height = $('.content_box').height(); 
  // "colio" plugin
  $('.audio_albums .album_list').colio({
    id: 'demo_1',
    theme: 'black',
    placement: 'inside',
    onExpand: function(){
      $content_box.height( content_box_height + $(this).height() );
    },
    onCollapse: function(){
      $content_box.height( content_box_height );
    }
  }); 
});

     
  </script>
     
</div>
  

app/views/videos/index.js.erb
$("#video_render").html("<%= escape_javascript(render("videos")) %>");

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<!--<div class="row">
   <div class="col-md-12">
     <% @videos.each do |video| %>
          <td><%= link_to image_tag(video.video_url(:thumb)), video_path(video)%></td>
    <% end %>
  </div>
</div>-->
<div>
  <% if @videosall.count==0%>
  <div><center><h4>No videos</h4></center></div>
  <% else %>
    <% @video_first_id=@video_first.id %>
    <% @videos_remain=@videosall.where('id NOT IN(?)', @video_first_id) %>    
    <div class="hidden-lg">
      <div id="owl-demo" class="owl-carousel">
      <% @videosall.each do |video| %>
        <div class="item"> <a href="<%= video_path(video) %>"><%= image_tag video.video_url(:thumb) , :class => "img-responsive" %></a><center><%= video.name%></center> </div>
       <%end%> 
      </div>
  </div>
  <!-- slider for  videos -->
  <div class="row visible-lg" >
    <center><h3>Jukebox</h3></center>
    <div class="carousel slide" id="myCarousel" >
      <div class="carousel-inner" style="height:110px">
        
        <div class="item active" >
          <div class="col-lg-3"><a href="<%= video_path(@video_first) %>">
          <%= image_tag @video_first.video_url(:thumb) , :class => "img-responsive" %></a></div>
        </div>
        <% @videos_remain.each do |video| %>
        <div class="item" >
          <div class="col-lg-3"><a href="<%= video_path(video) %>"><%= image_tag video.video_url(:thumb) , :class => "img-responsive" %></a></div>
        </div>
        <%end%>
        
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>

    </div>
  </div>
  <% end %>
</div>


<br>

<div class="row">
   
    <%= render "shared/video" %>
   
</div>

<br>



<div class="row">
  <% @videos_bottom_pagiantion.each do |video|  %>
    <div class="col-xs-6 col-md-3">
      <a class="thumbnail" href="<%= video_path(video) %>">
      <%= video.name %>
      <%= image_tag video.video_url(:thumb) , :class => "img-responsive" %></a>
    </div>
  <% end %>
  </div>

<div class="row">
<center>
  <%= will_paginate @videos_bottom_pagiantion,renderer: BootstrapPagination::Rails, :page_links => false , remote: true %>
  </center>
</div>



 <div class="row">
<%#= render_shareable  %>
<%= twitter_button %>
</div>