config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {registrations: 'registrations',sessions: 'sessions',omniauth_callbacks: "omniauth_callbacks"}
  resources :sliders

  resources :news
  #get 'friends/new'
  resources :mailbox   
  resources :friends  
  resources :contacts 

  resources :categories do
    resources :bibles do
      resources :chapters
    end
  end

  # resources :bibles do
  #   resources :chapters
  # end

  get 'radio/index'

  resources :audios 

  resources :albums do
    resources :audios  
  end 
  get 'welcome/album_url'
  get 'welcome/video_details'
  get 'welcome/audio_details'
  get 'welcome/album_details'
  resources :daily_breads
  resources :videos
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/contact'
    get 'welcome/about'
  # devise_for :admins  
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class News < ActiveRecord::Base
	validates :title, presence: true
    validates :content, presence: true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.order("created_at DESC")
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<center><h1>News</h1></center>

  
    <% @news.each do |news| %>
      <div class="list_contact">
        <h4> <%= news.title %></h4>
        <b><%= news.created_at.strftime("%d/%m/%Y") %>&nbsp&nbsp&nbsp&nbsp<%="#{time_ago_in_words(news.created_at)} ago "%></b>
        <p><%= news.content %></p> 
      </div>
    <% end %>
  

<br>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>