config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => {registrations: 'registrations',sessions: 'sessions',omniauth_callbacks: "omniauth_callbacks"}
  resources :sliders

  resources :news
  #get 'friends/new'
  resources :mailbox   
  resources :friends  
  resources :contacts 

  resources :categories do
    resources :bibles do
      resources :chapters
    end
  end

  # resources :bibles do
  #   resources :chapters
  # end

  get 'radio/index'

  resources :audios 

  resources :albums do
    resources :audios  
  end 
  get 'welcome/album_url'
  get 'welcome/video_details'
  get 'welcome/audio_details'
  get 'welcome/album_details'
  resources :daily_breads
  resources :videos
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/contact'
    get 'welcome/about'
  # devise_for :admins  
  devise_for :admins, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
end

app/models/daily_bread.rb
# == Schema Information
#
# Table name: daily_breads
#
#  id         :integer          not null, primary key
#  message    :string
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#  audio      :string
#

class DailyBread < ActiveRecord::Base

	validates :date, uniqueness: true
	mount_uploader :message, ImageUploader
	mount_uploader :audio, BreadAudioUploader

	 validates :date, :presence => true
 	 validates :audio, :presence => true
 	 validates :message, :presence => true

 	def previous_bread
  		DailyBread.where("id > ?", self.id).order("id ASC").first || DailyBread.first
	end

	def next_bread
  		    DailyBread.where("id < ?", self.id).order("id DESC").first || DailyBread.last
	end
end

app/controllers/daily_breads_controller.rb
  class DailyBreadsController < ApplicationController
     before_action :set_daily_bread, only: [:show, :edit, :update, :destroy]
     before_filter :loged_in?, :only => [:new,:create, :edit, :destroy]
      before_filter :set_search

  # GET /DailyBreads
  # GET /DailyBreads.json
  def index  
     if params[:q]
        @search=DailyBread.search(params[:q])
        @daily_breads =  @search.result
    else
          @daily_breads=DailyBread.where(date: Date.today.strftime("%Y-%m-%d"))
    end
  end

  # GET /DailyBreads/1
  # GET /DailyBreads/1.json
  def show
      if params[:q]
        @search=DailyBread.search(params[:q])
        @daily_breads =  @search.result
    else
          @daily_breads=DailyBread.where(date: Date.today.strftime("%Y-%m-%d"))
    end
  end

 

  def set_search
    @search=DailyBread.search(params[:q])
  end


  def new
    @daily_bread = DailyBread.new
  end


  def edit
  end


  # DailyBread /DailyBreads
  # DailyBread /DailyBreads.json
  def create
    @daily_bread = DailyBread.new(daily_bread_params)

    respond_to do |format|
      if @daily_bread.save
        format.html { redirect_to @daily_bread, notice: 'DailyBread was successfully created.' }
        format.json { render :show, status: :created, location: @daily_bread }
      else
        format.html { render :new }
        format.json { render json: @daily_bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /DailyBreads/1
  # PATCH/PUT /DailyBreads/1.json
  def update
    respond_to do |format|
      if @daily_bread.update(daily_bread_params)
        format.html { redirect_to @daily_bread, notice: 'DailyBread was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_bread }
      else
        format.html { render :edit }
        format.json { render json: @daily_bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /DailyBreads/1
  # DELETE /DailyBreads/1.json
  def destroy
    @daily_bread.destroy
    respond_to do |format|
      format.html { redirect_to daily_breads_url, notice: 'DailyBread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_bread
      @daily_bread = DailyBread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_bread_params
     params.require(:daily_bread).permit(:message, :date)
    end
    def loged_in?
      redirect_to root_path
    end
     
 
end

app/helpers/daily_breads_helper.rb
module DailyBreadsHelper

end

app/views/daily_breads/_form.html.erb
<%= simple_form_for(@daily_bread) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :message %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/daily_breads/edit.html.erb
<h1>Editing daily_bread</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_bread %> |
<%= link_to 'Back', daily_breads_path %>
<!-- CONTENT BLOCK { -->
<div class="content_box yellow_box">
  
    <div class="main_head page_head text-center">
      <h1 class="head_1 animated" data-gen="fadeInUp">Daily Bread</h1>
    </div>
    
    <div class="clearfix"></div>
    
    <section class="block_1 margin_t15 padding_t10">
      <div class="bible_head">
          <div class="bible_chpthead">
              <div class="col-sm-12">
               <% @daily_breads.each do |bread| %>
                   
                  <a href="#" title="previous page" class="page_nav pre_page"><img src="images/arrowl.png" width="29" height="29" alt=""/></a>
                  <% end %>
                  <div class="page_selector">
                        <p>111111111111111111</p>
                        <div class="cal_cont"> 
                           <div id="search_box" ></div>
                        </div> 
                    </div>
                    
                  <a href="#" title="next page" class="page_nav nxt_page"><img src="images/arrowr.png" width="29" height="29" alt=""/></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        
        <div class="bible_paper bible_norm">
          <div class="bible_page">
              <div class="bible_pageimg"> 
               <% @daily_breads.each do |bread| %>
                <img src="<%= bread.message %>" width="510" height="822" alt=""/>
                
                  <div class="nav_bible">
                      <a href="#" class="prev_page"></a>
                        <a href="#" class="next_page"></a>              
                  </div>
                    <% end %>
                </div>
                <div class="clearfix"></div>
                
                <div class="candles cendle_left">
                    <img src="assets/bible/candle-left.png" width="86" height="554" alt=""/>
                </div>
                <div class="candles cendle_right">
                    <img src="assets/bible/candle-right.png" width="86" height="554" alt=""/>
                </div>
                <div class="bible_player" align="center">
               <div id="jp_container_4" class="jp-video jp-video-270p">
      <div class="jp-type-playlist">
        <div id="jquery_jplayer_4" class="jp-jplayer"></div>
        <div class="jp-gui">
          <div class="jp-video-play">
            <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
          </div>
          <div class="jp-interface">
            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>
            <div class="jp-current-time"></div>
            <div class="jp-duration"></div>
            <div class="jp-details">
              <ul>
                <li><span class="jp-title"></span></li>
              </ul>
            </div>
            <div class="jp-controls-holder">
              <ul class="jp-controls">
               
                <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
              </ul>
              <div class="jp-volume-bar">
                <div class="jp-volume-bar-value"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="jp-playlist">
        </div>
        <div class="jp-no-solution">
          <span>Update Required</span>
          To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
      </div>
    </div>
</div></div>
                
            </div>
            <div class="clearfix"></div>
        </div>
    </section>
    
</div>
<!-- CONTENT BLOCK } -->



 









 



 







  

app/views/daily_breads/index.html.erb
<!-- CONTENT BLOCK --> 
<div class="content_box yellow_box">
  
    <div class="main_head page_head text-center">
      <h1 class="head_1 animated" data-gen="fadeInUp">Daily Bread</h1>
    </div>
    
    <div class="clearfix"></div>
    
    <section class="block_1 margin_t15 padding_t10">
      <div class="bible_head">
          <div class="bible_chpthead">
              <div class="col-sm-12 search_box_height"> 
                  <div class="page_selector">
                       <%= search_form_for @search,   :id => "search_form"  do |f| %>
                         <%= f.text_field :date_cont , :id  => 'search_box', :readonly => true %>
                        <% end %>
                    </div> 
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        
        <div class="bible_paper bible_norm">
          <div class="bible_page">
              <div class="bible_pageimg"> 
               <% @daily_breads.each do |bread| %>
                <img src="<%= bread.message %>" width="510" height="822" alt=""/>
                
                  <div class="nav_bible">
                      <!-- <a href="#" class="prev_page"></a>
                        <a href="#" class="next_page"></a> -->              
                  </div>
                    <% end %>
                </div>
                <div class="clearfix"></div>
                
                <div class="candles cendle_left">
                    <img src="assets/bible/candle-left.png" width="86" height="554" alt=""/>
                </div>
                <div class="candles cendle_right">
                    <img src="assets/bible/candle-right.png" width="86" height="554" alt=""/>
                </div>
                <div class="bible_player" align="center">
               <div id="jp_container_4" class="jp-video jp-video-370p">
                  <div class="jp-type-playlist">
                    <div id="jquery_jplayer_4" class="jp-jplayer"></div>
                    <div class="jp-gui">
                      <div class="jp-video-play">
                        <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                      </div>
                      <div class="jp-interface">
                        <div class="jp-progress">
                          <div class="jp-seek-bar">
                            <div class="jp-play-bar"></div>
                          </div>
                        </div>
                        <div class="jp-current-time"></div>
                        <div class="jp-duration"></div>
                        <div class="jp-details">
                          <ul>
                            <li><span class="jp-title"></span></li>
                          </ul>
                        </div>
                        <div class="jp-controls-holder">
                          <ul class="jp-controls">
                           
                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                          </ul>
                          <div class="jp-volume-bar">
                            <div class="jp-volume-bar-value"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="jp-playlist">
                    </div>
                    <div class="jp-no-solution">
                      <span>Update Required</span>
                      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                    </div>
                  </div>
                </div>
              </div>
            </div> 
                
          </div>
          <div class="clearfix"></div>
      </div>
  </section>
    
</div>
<!-- CONTENT BLOCK }

app/views/daily_breads/new.html.erb
<h1>New daily_bread</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_breads_path %>

app/views/daily_breads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @daily_bread.message %>
</p>

<p>
  <strong>Date:</strong>
  <%= @daily_bread.date %>
</p>


<%= link_to("Previous ", @daily_bread.previous_bread) if @daily_bread.previous_bread %>
<%= link_to("Next ", @daily_bread.next_bread) if @daily_bread.next_bread %>

<%= link_to 'Edit', edit_daily_bread_path(@daily_bread) %> |
<%= link_to 'Back', daily_breads_path %>